### ISSUE TITLE
Rename to Body & Add BREAKING CHANGE

### ISSUE THREAD

**Issue by digitalAssetStore** [arnoldlorincz/VSConventionalCommitMessageHelper#1]
I have two remarks/proposals for further improvement

1) Rename "Description" to "Body"
The specification (www.conventionalcommits.org) uses also "Body" not "~~Description~~".

2) Can you add an input-box for a footer "BREAKING CHANGE"
Like described in www.conventionalcommits.org.

Thanks in advance

**Comment by arnoldlorincz** [comment]
Thanks for the suggestions, I will definitely do these changes next week and release a new version.

Have a great day!
