### ISSUE TITLE
Plan to update this project to VS 2022 ?

### ISSUE THREAD

**Issue by dotdiego** [arnoldlorincz/VSConventionalCommitMessageHelper#2]
Hello,
I think that you have the only extension that does this functionality on the Visual Studio Marketplace.
Do you have any plan to support VS 2022 ?

Regards,

**Comment by arnoldlorincz** [comment]
Hey,
Yes, I do plan to update it, I just didn’t had time yet.

**Comment by saigkill** [comment]
Anything new from the 2022 extension? Would be great if it can used there soon :-)

**Comment by arnoldlorincz** [comment]
Hey @saigkill, yes, I'm working on it. I had a couple of issues after upgrading but it seems I managed to fix it. Hopefully it will be ready in a couple of hours.
